export const tasks = [
  {
    id: 1,
    name: 'Task 1',
    created: 123,
    category: 'Task',
    content: 'Lorem ipsum',
    isArchieved: false,
  },
  {
    id: 2,
    name: 'Task 2',
    created: 123,
    category: 'Random Thought',
    content: 'Lorem ipsum',
    isArchieved: false,
  },
  {
    id: 3,
    name: 'Task 3',
    created: 123,
    category: 'Task',
    content: 'Lorem ipsum',
    isArchieved: false,
  },
  {
    id: 4,
    name: 'Task 4',
    created: 123,
    category: 'Idea',
    content: 'Lorem ipsum',
    isArchieved: false,
  },
  {
    id: 5,
    name: 'Task 5',
    created: 123,
    category: 'Quote',
    content: 'Lorem ipsum',
    isArchieved: true,
  },
  {
    id: 6,
    name: 'Task 6',
    created: 123,
    category: 'Quote',
    content: 'Lorem ipsum',
    isArchieved: true,
  },
];
